name = "QuantumGaussianDynamics"
uuid = "b5781b8a-c3cd-49e3-88b7-4e99ca02a1de"
authors = ["Francesco Libbi <libbi@g.harvard.edu>", "Lorenzo Monacelli <lorenzo.monacelli@epfl.ch>"]
version = "1.0.0-dev"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
julia = "1.11"
MPI = "0.20"
OptimizationOptimJL = "0.4"
PyCall = "1.96"
Roots = "2.2"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
